/*  MBTA Bus Route 1
    Harvard Square to Nubian Station
*/

var busLine = [
  {stop: 1, station: 'Washington St opp Ruggles St'},
  {stop: 2, station: 'Washington St @ Melnea Cass Blvd'},
  {stop: 6, station: 'Melnea Cass Blvd @ Harrison Ave'},
  {stop: 10003, station: 'Albany St opp Randall St'},
  {stop: 57, station: 'Massachusetts Ave @ Albany St'},
  {stop: 58, station: 'Massachusetts Ave @ Harrison Ave'},
  {stop: 10590, station: 'Massachusetts Ave @ Washington St'},
  {stop: 87, station: 'Massachusetts Ave @ Tremont St'},
  {stop: 188, station: 'Massachusetts Ave @ Massachusetts Ave Station'},
  {stop: 89, station: 'Massachusetts Ave @ St Botolph St'},
  {stop: 91, station: 'Massachusetts Ave @ Clearway St'},
  {stop: 93, station: 'Massachusetts Ave @ Newbury St'},
  {stop: 95, station: 'Massachusetts Ave @ Beacon St'},
  {stop: 97, station: '77 Massachusetts Ave'},
  {stop: 99, station: 'Massachusetts Ave @ Albany St'},
  {stop: 101, station: 'Massachusetts Ave @ Sidney St'},
  {stop: 102, station: 'Massachusetts Ave @ Prospect St'},
  {stop: 104, station: 'Massachusetts Ave @ Bigelow St'},
  {stop: 106, station: 'Massachusetts Ave @ Hancock St'},
  {stop: 107, station: 'Massachusetts Ave @ Dana St'},
  {stop: 108, station: 'Massachusetts Ave @ Trowbridge St'},
  {stop: 109, station: 'Massachusetts Ave @ Bow St'},
  {stop: 64, station: 'Nubian Station'},
  {stop: 63, station: 'Washington St opp Ruggles St'},
  {stop: 62, station: 'Washington St @ Williams St'},
  {stop: 10101, station: 'Melnea Cass Blvd @ Harrison Ave'},
  {stop: 10100, station: 'Albany St opp Randall St'},
  {stop: 856, station: 'Massachusetts Ave @ Albany St'},
  {stop: 854, station: 'Massachusetts Ave @ Harrison Ave'},
  {stop: 59, station: 'Massachusetts Ave @ Washington St'},
  {stop: 84, station: 'Massachusetts Ave @ Tremont St'},
  {stop: 187, station: 'Massachusetts Ave @ Massachusetts Ave Station'},
  {stop: 82, station: 'Massachusetts Ave @ Huntington Ave'},
  {stop: 80, station: 'Massachusetts Ave opp Christian Science Ctr'},
  {stop: 79, station: 'Massachusetts Ave @ Boylston St'},
  {stop: 77, station: 'Massachusetts Ave @ Marlborough St'},
  {stop: 75, station: '84 Massachusetts Ave'},
  {stop: 74, station: 'Massachusetts Ave @ Albany St'},
  {stop: 73, station: 'Massachusetts Ave @ Sidney St'},
  {stop: 72, station: 'Massachusetts Ave @ Pearl St'},
  {stop: 71, station: 'Massachusetts Ave opp Inman St'},
  {stop: 69, station: 'Massachusetts Ave @ Hancock St'},
  {stop: 68, station: 'Massachusetts Ave @ Bay St'},
  {stop: 67, station: 'Mt Auburn St @ Putnam Ave'},
  {stop: 66, station: 'Mt Auburn St @ DeWolfe St'},
  {stop: 110, station: 'Massachusetts Ave @ Holyoke St'},
];